/**
 */
package DataWeb.provider;

import DataWeb.util.DataWebAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITableItemLabelProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DataWebItemProviderAdapterFactory extends DataWebAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DataWebItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
		supportedTypes.add(ITableItemLabelProvider.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.Aplicacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AplicacionItemProvider aplicacionItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.Aplicacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAplicacionAdapter() {
		if (aplicacionItemProvider == null) {
			aplicacionItemProvider = new AplicacionItemProvider(this);
		}

		return aplicacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.Entidad} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntidadItemProvider entidadItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.Entidad}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntidadAdapter() {
		if (entidadItemProvider == null) {
			entidadItemProvider = new EntidadItemProvider(this);
		}

		return entidadItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.Rol} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RolItemProvider rolItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.Rol}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRolAdapter() {
		if (rolItemProvider == null) {
			rolItemProvider = new RolItemProvider(this);
		}

		return rolItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.Atributo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtributoItemProvider atributoItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.Atributo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtributoAdapter() {
		if (atributoItemProvider == null) {
			atributoItemProvider = new AtributoItemProvider(this);
		}

		return atributoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.PaginaInicio} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PaginaInicioItemProvider paginaInicioItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.PaginaInicio}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPaginaInicioAdapter() {
		if (paginaInicioItemProvider == null) {
			paginaInicioItemProvider = new PaginaInicioItemProvider(this);
		}

		return paginaInicioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.PaginaCreacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PaginaCreacionItemProvider paginaCreacionItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.PaginaCreacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPaginaCreacionAdapter() {
		if (paginaCreacionItemProvider == null) {
			paginaCreacionItemProvider = new PaginaCreacionItemProvider(this);
		}

		return paginaCreacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.PaginaDetalle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PaginaDetalleItemProvider paginaDetalleItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.PaginaDetalle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPaginaDetalleAdapter() {
		if (paginaDetalleItemProvider == null) {
			paginaDetalleItemProvider = new PaginaDetalleItemProvider(this);
		}

		return paginaDetalleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.PaginaActualizacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PaginaActualizacionItemProvider paginaActualizacionItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.PaginaActualizacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPaginaActualizacionAdapter() {
		if (paginaActualizacionItemProvider == null) {
			paginaActualizacionItemProvider = new PaginaActualizacionItemProvider(this);
		}

		return paginaActualizacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.PaginaBorrado} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PaginaBorradoItemProvider paginaBorradoItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.PaginaBorrado}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPaginaBorradoAdapter() {
		if (paginaBorradoItemProvider == null) {
			paginaBorradoItemProvider = new PaginaBorradoItemProvider(this);
		}

		return paginaBorradoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.PaginaIndice} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PaginaIndiceItemProvider paginaIndiceItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.PaginaIndice}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPaginaIndiceAdapter() {
		if (paginaIndiceItemProvider == null) {
			paginaIndiceItemProvider = new PaginaIndiceItemProvider(this);
		}

		return paginaIndiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.PaginaIndiceDetalle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PaginaIndiceDetalleItemProvider paginaIndiceDetalleItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.PaginaIndiceDetalle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPaginaIndiceDetalleAdapter() {
		if (paginaIndiceDetalleItemProvider == null) {
			paginaIndiceDetalleItemProvider = new PaginaIndiceDetalleItemProvider(this);
		}

		return paginaIndiceDetalleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.PaginaEncuestaCuestionario} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PaginaEncuestaCuestionarioItemProvider paginaEncuestaCuestionarioItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.PaginaEncuestaCuestionario}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPaginaEncuestaCuestionarioAdapter() {
		if (paginaEncuestaCuestionarioItemProvider == null) {
			paginaEncuestaCuestionarioItemProvider = new PaginaEncuestaCuestionarioItemProvider(this);
		}

		return paginaEncuestaCuestionarioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.PaginaResultados} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PaginaResultadosItemProvider paginaResultadosItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.PaginaResultados}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPaginaResultadosAdapter() {
		if (paginaResultadosItemProvider == null) {
			paginaResultadosItemProvider = new PaginaResultadosItemProvider(this);
		}

		return paginaResultadosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.Pregunta} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PreguntaItemProvider preguntaItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.Pregunta}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPreguntaAdapter() {
		if (preguntaItemProvider == null) {
			preguntaItemProvider = new PreguntaItemProvider(this);
		}

		return preguntaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.EnlaceRRSS} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnlaceRRSSItemProvider enlaceRRSSItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.EnlaceRRSS}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnlaceRRSSAdapter() {
		if (enlaceRRSSItemProvider == null) {
			enlaceRRSSItemProvider = new EnlaceRRSSItemProvider(this);
		}

		return enlaceRRSSItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.PaginaIndiceExtendido} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PaginaIndiceExtendidoItemProvider paginaIndiceExtendidoItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.PaginaIndiceExtendido}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPaginaIndiceExtendidoAdapter() {
		if (paginaIndiceExtendidoItemProvider == null) {
			paginaIndiceExtendidoItemProvider = new PaginaIndiceExtendidoItemProvider(this);
		}

		return paginaIndiceExtendidoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link DataWeb.PaginaCRUDUnica} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PaginaCRUDUnicaItemProvider paginaCRUDUnicaItemProvider;

	/**
	 * This creates an adapter for a {@link DataWeb.PaginaCRUDUnica}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPaginaCRUDUnicaAdapter() {
		if (paginaCRUDUnicaItemProvider == null) {
			paginaCRUDUnicaItemProvider = new PaginaCRUDUnicaItemProvider(this);
		}

		return paginaCRUDUnicaItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (aplicacionItemProvider != null) aplicacionItemProvider.dispose();
		if (entidadItemProvider != null) entidadItemProvider.dispose();
		if (rolItemProvider != null) rolItemProvider.dispose();
		if (atributoItemProvider != null) atributoItemProvider.dispose();
		if (paginaInicioItemProvider != null) paginaInicioItemProvider.dispose();
		if (paginaCreacionItemProvider != null) paginaCreacionItemProvider.dispose();
		if (paginaDetalleItemProvider != null) paginaDetalleItemProvider.dispose();
		if (paginaActualizacionItemProvider != null) paginaActualizacionItemProvider.dispose();
		if (paginaBorradoItemProvider != null) paginaBorradoItemProvider.dispose();
		if (paginaIndiceItemProvider != null) paginaIndiceItemProvider.dispose();
		if (paginaIndiceDetalleItemProvider != null) paginaIndiceDetalleItemProvider.dispose();
		if (paginaEncuestaCuestionarioItemProvider != null) paginaEncuestaCuestionarioItemProvider.dispose();
		if (paginaResultadosItemProvider != null) paginaResultadosItemProvider.dispose();
		if (preguntaItemProvider != null) preguntaItemProvider.dispose();
		if (enlaceRRSSItemProvider != null) enlaceRRSSItemProvider.dispose();
		if (paginaIndiceExtendidoItemProvider != null) paginaIndiceExtendidoItemProvider.dispose();
		if (paginaCRUDUnicaItemProvider != null) paginaCRUDUnicaItemProvider.dispose();
	}

}
